# Generated by Django 3.0.5 on 2020-04-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Approved'),
        ),
    ]
