# Generated by Django 3.2.7 on 2021-10-02 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Item Name')),
                ('price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Discounted Price')),
                ('description', models.TextField(default=None, null=True)),
                ('additional_info', models.TextField(default=None, null=True, verbose_name='Additional Information')),
                ('featured_image', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Featured Image')),
                ('sub_image1', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image 1')),
                ('sub_image2', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image 2')),
                ('sub_image3', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image 3')),
                ('sub_image4', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image 4')),
                ('sub_image5', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image 5')),
                ('inventory', models.FloatField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
