# Generated by Django 2.2.2 on 2020-05-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.CharField(default='', max_length=10)),
                ('tag', models.CharField(choices=[('Featured', 'Featured'), ('AWS', 'AWS'), ('Python', 'Python'), ('Heroku', 'Heroku'), ('Bootstrap', 'Bootstrap'), ('Podcast', 'Podcast'), ('Workflow', 'Workflow')], default='Featured', max_length=100)),
                ('featured_image', models.ImageField(default='default.png', upload_to='blog_pics', verbose_name='Featured Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('preview', models.CharField(default='', max_length=5000)),
                ('time', models.CharField(default='', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
