# Generated by Django 3.2.7 on 2021-10-02 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('preview', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5, help_text='in minutes', verbose_name='Read Time')),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('Featured', 'Featured'), ('Data', 'Data'), ('Django', 'Django'), ('AR', 'AR'), ('VR', 'VR'), ('Database', 'Database'), ('Python', 'Python'), ('AWS', 'AWS'), ('Heroku', 'Heroku'), ('Git', 'Git')], default='Featured', max_length=100)),
                ('featured_image', models.ImageField(default='default.png', upload_to='blog_pics', verbose_name='Featured Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
