# Generated by Django 3.0.5 on 2020-05-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
