# Generated by Django 3.2.8 on 2026-02-24 22:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Featured', 'Featured'), ('Data', 'Data'), ('Django', 'Django'), ('AR', 'AR'), ('VR', 'VR'), ('Database', 'Database'), ('Python', 'Python'), ('AWS', 'AWS'), ('Heroku', 'Heroku'), ('Git', 'Git'), ('Physics', 'Physics'), ('Science', 'Science'), ('Case-Studies', 'Case-Studies')], default='Featured', max_length=100),
        ),
    ]
