# Generated by Django 3.2.8 on 2026-02-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20260224_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html_file',
            field=models.FileField(blank=True, null=True, upload_to='post_html_files/', verbose_name='Content HTML File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', help_text='You can also upload a .html file with the content. If both are provided, the .html file will be used.', null=True, verbose_name='Content'),
        ),
    ]
