# Generated by Django 3.0.5 on 2020-09-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=5, help_text='in minutes', verbose_name='Read Time'),
        ),
    ]
